homeserverUrl: "https://t2bot.io"
accessToken: "YOUR_TOKEN_HERE"
aliasDomain: "t2bot.io"

# Use wildcards to signify which aliases are allowed to be added by this bot.
# The domain part (:t2bot.io) is automatically added and checked.
allowedAliases:
- "#telegram_*"
- "#custom_*"

# These users can add any aliases they like through this bot. They must still have permission to
# add aliases in the room.
adminUsers:
- "@youraccount:matrix.org"

# Settings for controlling how logging works
logging:
  file: logs/aliasbot.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5