homeserverUrl: "https://t2bot.io"
accessToken: "YOUR_TOKEN_HERE"
aliasDomain: "t2bot.io"

# Use wildcards to signify which aliases are allowed to be added by this bot.
# The domain part (:t2bot.io) is automatically added and checked.
allowedAliases:
- "#telegram_*"
- "#custom_*"

# These users can add any aliases they like through this bot. They must still have permission to
# add aliases in the room.
adminUsers:
- "@youraccount:matrix.org"

# Where sync data and other related information should be stored
dataPath: "./storage"

# The help channel to advertise in the help menu for the bot. If empty, no help channel will be mentioned.
helpChannel: "#help:t2bot.io"

# Options for the provisioning API. The provisioning API allows someone to use the bot over an API
# instead of just the in-room commands.
provisioning:
  enabled: false
  bind: '0.0.0.0'
  port: 4502
  sharedSecret: 'CHANGE_ME'

# Settings for controlling how logging works
logging:
  file: logs/aliasbot.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5